server {
    listen 80;
    listen [::]:80;
    server_name suivicloud.xyz;

    include /etc/nginx/snippets/suivicloud-static.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name www.suivicloud.xyz;

    return 301 https://suivicloud.xyz$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name suivicloud.xyz;

    ssl_certificate /etc/ssl/suivicloud/suivicloud.xyz.crt;
    ssl_certificate_key /etc/ssl/suivicloud/suivicloud.xyz.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    include /etc/nginx/snippets/suivicloud-static.conf;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.suivicloud.xyz;

    ssl_certificate /etc/ssl/suivicloud/suivicloud.xyz.crt;
    ssl_certificate_key /etc/ssl/suivicloud/suivicloud.xyz.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    return 301 https://suivicloud.xyz$request_uri;
}
